### ISSUE TITLE
Error in gulpfile

### ISSUE THREAD

**Issue by borestad** [willianjusten/Fast#1]
Hi. Nice setup.
Just wanted to tell that you have an error (g character) in the last line of the gulpfile

<code>
gulp.task('buildfy', ['browserify', 'jade', 'stylus', 'imagemin', 'deploy']);g
</code>

Best regards
Johan

**Comment by willianjusten** [comment]
Hey thanks!! I use "g ca" to commit..failed xDD

**Comment by willianjusten** [comment]
Fixed [2a32de5e34c4296ab4e1fa103f23d71cc464b5f7](https://github.com/willianjusten/Fast/commit/2a32de5e34c4296ab4e1fa103f23d71cc464b5f7)
