### ISSUE TITLE
[DÚVIDA] Sobre normalize() no main.styl

### ISSUE THREAD

**Issue by filipeltsilva** [willianjusten/Fast#4]
Como implementar esse normalize(), que imagino ser o CSS reset, que está sendo chamado no arquivo src/styl/main.styl? Não ficou muito claro pra mim.

**Comment by willianjusten** [comment]
Ele vem do [Kouto Swiss](http://kouto-swiss.io/docs.html#normalize), que é um plugin que utilizo no Stylus.
